### ISSUE TITLE
Make it possible to use several dictionary files

### ISSUE THREAD

**Issue by tobsan** [sphinx-contrib/spelling#10]
For example, when having a project that includes some docs using spelling in another project and one doesn't want to duplicate all words in the spelling file.

Would be nice to be able to say:

`spelling_word_list_filename=['spelling_wordlist.txt', 'other_wordlist.txt']`

**Comment by dhellmann** [comment]
This would make a good enhancement. Let me know if you want to work on the patch(es) to implement it.

**Comment by tobsan** [comment]
I can start implementing it right away!

**Comment by tobsan** [comment]
I suppose the easiest way would be to use the first list and then add every word of every other list, since it looks like `enchant.DictwithPWL` doesn't support more than one list.

**Comment by dhellmann** [comment]
Excellent, I'm happy to help with reviews.

Yes, building a combined list in some way sounds like it makes the most sense.

**Comment by tobsan** [comment]
@dhellmann I have a sample solution ready but I haven't been able to run the tests properly. How does your setup look wrt testing? Should I uninstall the plugin from pip first, etc?

**Comment by tobsan** [comment]
Nvm, found "make test". Will add to the README or something.

**Comment by dhellmann** [comment]
You should be able to run the tests by just running "tox".

**Comment by tobsan** [comment]
I found it by looking through the Makefile. See #11
