### ISSUE TITLE
Encoding error: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by mwtoews** [sphinx-contrib/spelling#121]
This issue was found after updating a docker container (osgeo/proj:latest) used to build docs; see
https://github.com/OSGeo/PROJ/runs/2088960048?check_suite_focus=true#step:10:32 for error message:
```
Encoding error:
'ascii' codec can't encode character '\u201c' in position 39: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-cab77k47.log, if you want to report the issue to the developers.
```
Repeating locally to see the full log shows that this container's version of Python 3.6.9 behaves differently than expected:
```
$ python3 -c "from imp import find_module; find_module('\u201cfoo')"
```
should normally raise:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '“foo'
```
but with the container raises:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/imp.py", line 286, in find_module
    if os.path.isfile(file_path):
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 0: ordinal not in range(128)
```
---
A terrible hack (for now) is to quickly patch up:
```
sed -i '188s/except ImportError/except \(ImportError, UnicodeError\)/' /usr/local/lib/python3.6/dist-packages/sphinxcontrib/spelling/filters.py
```
which modifies https://github.com/sphinx-contrib/spelling/blob/76127431a996ee6f69fc43f359404a9ca488c9dd/sphinxcontrib/spelling/filters.py#L188
to
```python
            except (ImportError, UnicodeError):
```
Ideally, an upstream fix should come from this package. I'll let the devs here provide a better fix than my 1-liner hack.

**Comment by dhellmann** [comment]
You need to set the locale variables inside the container to values that support the encoding of the content you're processing. Something like this should do it

```
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
```

**Comment by mwtoews** [comment]
Thanks for the quick response! For my particular situation based on `ubuntu:18.04`, [this answer](https://stackoverflow.com/a/38553499) resolved the issue.
