### ISSUE TITLE
is there a verbose options ? 

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/spelling#122]
I work on a rather big documentation and as my colleagues are not aware of .rst format they send me huge piece of doc in .docx, .txt, .md... It means that sometime I create in one batch thousands of lines with thousands of misspelled word (mainly Geospatial words that I need to add to the dictionary). So when I run the following command:

```
make spelling
```

I get an avalanche of output in my terminal. I'm very happy with the `spelling` folder created within the build directory and would just like to have the build information displayed in the terminal, not the content of the `.spelling` files. Is it already possible ? 

If not is it something you would consider as an enhancement ?

**Comment by dhellmann** [comment]
Those log messages come from https://github.com/sphinx-contrib/spelling/blob/master/sphinxcontrib/spelling/builder.py#L219-L222

Normally I would want to see the output, but I can understand how in your case it is excessive, so I could see adding a log level option to supersede the existing `spelling_warning` option. I would be happy to review a PR, if you want to work on that.

**Comment by 12rambau** [comment]
I'll try to find the time to make a PR as you show me where to look. 
At the moment I'm the only one requesting it so there is no rush !
