### ISSUE TITLE
Build errors with version 7.3.1

### ISSUE THREAD

**Issue by cas--** [sphinx-contrib/spelling#142]
Our CI picked up the latest version and is now erroring https://github.com/deluge-torrent/deluge/runs/4661496830?check_suite_focus=true

```
sphinx-build -v -j auto -b spelling -d docs/build/doctrees docs/source docs/build/spelling
Running Sphinx v4.3.2
Initializing Spelling Checker 7.3.1
...
usage: sphinx-build [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: sphinx-build --help [cmd1 cmd2 ...]
   or: sphinx-build --help-commands
   or: sphinx-build cmd --help

error: option -j not recognized
```

I am not sure what the exact issue is but reverting to 7.3.0 fixes the issues.

**Comment by manoelmarques** [comment]
I get the same error with command: `sphinx-build -M spelling docs docs/_build`
This time it is the option`-M` that is not recognized.
Changing to `-b` produces the same error with `-b` not recognized.
I reverted to 7.3.0 as well.

**Comment by dhellmann** [comment]
I'm preparing a 7.3.2 release right now.
