### ISSUE TITLE
Writing to a file  the warnings and suggestions

### ISSUE THREAD

**Issue by Corfucinas** [sphinx-contrib/spelling#145]
Is it possible to write to a **file** rather than only the stout warnings and suggestions? This would make it simpler to fix them.

**Comment by dhellmann** [comment]
For files with errors, the builder creates a file in the output directory using the extension `.spelling`.

https://github.com/sphinx-contrib/spelling/blob/master/sphinxcontrib/spelling/builder.py#L165

**Comment by Corfucinas** [comment]
Thanks!
