### ISSUE TITLE
Allow a limit for spelling_show_suggestions

### ISSUE THREAD

**Issue by tgross35** [sphinx-contrib/spelling#151]
It would be nice if there were a word limit for spelling_show_suggestions - maybe to show the 5 most relevant suggestions or something like that. Sometimes there are 15+ suggestions, and it can be quite a lot to look through.

Alternatively (or in addition), it could be better to see the suggestions list at the end, after the context statement

**Comment by dhellmann** [comment]
Wow, yeah, I've never had more than a few suggestions. I'd be happy to have a PR that limited the output, either based on a fixed number or based a configurable value.

**Comment by dhellmann** [comment]
This work was released in 7.5.0
