### ISSUE TITLE
Custom dictionary not being read

### ISSUE THREAD

**Issue by ronstone2000** [sphinx-contrib/spelling#152]
Hi,

I am running the spelling extension with a custom dictionary. Both the dictionary and conf.py are in the same directory: `source/conf.py` and `source/custom_wordlist.txt`.

in conf.py:

`spelling_word_list_filename = ['custom_wordlist.txt'] `

When I run a spell check, sphinx reports that it is looking for this file and then continues without error, so I assume it is found.

My issue is that the entire word list is ignored in the spelling report. For example, "Kubernetes" is listed, but is reported as a spelling error dozens of times.

Words in the file are one per line without spaces, numerics etc.

Any suggestions appreciated.

**Comment by ronstone2000** [comment]
Unfortunately no, this is not public. Here is some more detail on the setup:

In tox.ini we set a flag to conditionally load the spelling extension:
 
```
[testenv:spellcheck]
deps =
  -r{toxinidir}/doc/requirements.txt
  sphinxcontrib-spelling==7.3.2
commands =
         sphinx-build -a -E --keep-going -d doc/build/doctrees -t platform -t use_spellext -b spelling doc/source doc/build/spelling
 
```
in /doc/source/conf.py
 
```
if tags.has('use_spellext'):
    extensions.append('sphinxcontrib.spelling')
    spelling_word_list_filename='spelling_wordlist.txt'
```
 
```
grep Kubernetes /doc/source/spelling_wordlist.txt
Kubernetes
```

... but all terms in  /doc/source/spelling_wordlist.txt are ignored.

```
tox -e spellcheck
[snip]
spellcheck runtests: commands[10] | sphinx-build -a -E --keep-going -d doc/build/doctrees -t platform -t use_spellext -b spelling doc/source doc/build/spelling
Running Sphinx v4.2.0
[openstackdocstheme] version: 2.3.0
[openstackdocstheme] connecting html-page-context event handler
Initializing Spelling Checker 7.3.2
Ignoring wiki words
Ignoring acronyms
Ignoring Python builtins
Ignoring importable module names
Ignoring contributor names
Looking for custom word list in /doc/source/spelling_wordlist.txt
Scanning contributors
[snip]
… pods-general-considerations.rst:11: Spell check: Kubernetes: The Kubernetes limit for pods on a host is 
```

**Comment by ronstone2000** [comment]
No - native ubuntu.

**Comment by ronstone2000** [comment]
Problem solved. Turned out the file had Windows line ends. dos2unix was all it took to get going. Thanks for looking at this.

**Comment by dhellmann** [comment]
Ah, good, I'm glad you figured it out.
