### ISSUE TITLE
Wrong file name reported for spelling error in included file.

### ISSUE THREAD

**Issue by pgerell** [sphinx-contrib/spelling#153]
How to reproduce
============

Add an `.. include` directive to customize.rst

``` rst

.. spelling::

   wikis

=======================
 Configuration Options
=======================

These options can be set in ``conf.py`` along with the other Sphinx
configuration settings.

.. include:: test.txt
 
```

Create the file test.txt

```
Test of included file with incorect spelling

```

Warning message has the correct line number but the wrong filename.
```
X:\spelling\docs\source\customize.rst:1: Spell check: incorect: ["incorrect", "correction", "corrector", "injector", "correct"]: Test of included file with incorect spelling.
```

**Comment by dhellmann** [comment]
I think I have this fixed. Please give #155 a try (it's merged into the main branch, too) and let me know if that works for you. If it does, I'll prepare a release.

**Comment by pgerell** [comment]
Thank you, 

> I think I have this fixed. Please give #155 a try (it's merged into the main branch, too) and let me know if that works for you. If it does, I'll prepare a release.

It works as expected. Thank you
