### ISSUE TITLE
Excessive printing

### ISSUE THREAD

**Issue by transegn** [sphinx-contrib/spelling#193]
Hello,

This extension has been incredibly helpful and caught many typos for us! It appears that a debugging print statement has been leftover that is causing excessive printing. This is an issue for e.g. gitlab CI where it saturates the console log. To that point I'd request a way to disable this e.g. by wrapping it in a `verbosity` setting, since I really don't need to know that the directive is working as expected.

Thanks, 
Tom

https://github.com/sphinx-contrib/spelling/blob/7ca2924bc58bd9a63ee2def12a519c427f5f9367/sphinxcontrib/spelling/directive.py#L21

**Comment by transegn** [comment]
I'm happy to make the change myself early next week! If it's ok with you, I'd also propose to wrap the logging of e.g. "extending dictionary for file" in a configuration setting (which defaults to true for backwards compatibility) so that you can get a less verbose run. Especially when the builder is not `spelling` and the directive is filling a dictionary that will not be used. 

Tom

**Comment by dhellmann** [comment]
The fix for this is being released in 7.6.2.
