### ISSUE TITLE
Directive of Sphinx extension sphinx.ext.todo fails in spell check

### ISSUE THREAD

**Issue by cpetersd** [sphinx-contrib/spelling#203]
I am using the Sphinx extension `sphinx.ext.todo` and configured that accordingly in `conf.py`. 

```
extensions = [
    "sphinx.ext.todo",
    "sphinxcontrib.spelling",
]
````

Using the `..TODO::` directive of `sphinx.ext.todo`  in a test file called doc\test.rst results in a spell check failure.

doc\test.rst
`.. TODO:: Go shopping`

output:
`doc\test.rst:1: : Spell check: Todo: Todo.`

**Comment by dhellmann** [comment]
It looks like the text output of that plugin is inserting the word "Todo" into the stream that the spelling checker is reviewing. You could verify that by running with a higher verbosity setting.

I can't imagine being able to keep up with how every other sphinx extension mutates the input files, unfortunately. I recommend adding the word to your global words list as a way to work around the problem.

**Comment by cpetersd** [comment]
@dhellmann, thanks for the quick reply. Was not able to verify that yet but will look into that again and can let you know. I will just add the word to my words list as you recommended.

**Comment by dhellmann** [comment]
@cpetersd , please re-open this issue if you're still having trouble.
