### ISSUE TITLE
Support for the German letter ß missing?

### ISSUE THREAD

**Issue by kassbohm** [sphinx-contrib/spelling#218]
I use:

`spelling_lang='de'`

and:

`sphinx-build -b spelling ...`

However: Many German words written with the letter [ß](https://en.wikipedia.org/wiki/%C3%9F) are shown as misspelled...

**Comment by dhellmann** [comment]
This project is really just a wrapper for enchant, so it depends on that tool and its dictionaries. Does enchant report the same words as misspelled when run directly on the file?

**Comment by kassbohm** [comment]
Thanks for this.

Tested enchant like this:

`import enchant

# works fine:
d = enchant.Dict('de_DE')

# does produce spelling mistakes for words with the letter ß:
d = enchant.Dict('de')

# Example:
tmp = d.check("heiß") # German word for "hot"
print(tmp)
`

So now I use:
`spelling_lang='de'`
in my conf.py instead.

And it works fine.

**Comment by dhellmann** [comment]
Excellent, I'm glad you got it working!
