### ISSUE TITLE
Dealing with contractions such as "didn't"

### ISSUE THREAD

**Issue by astrofrog** [sphinx-contrib/spelling#22]
At the moment, I'm having issues with this package correctly recognizing valid contractions such 
as ``doesn't`` or ``didn't`` - it will flag up ``doesn`` as being an incorrect spelling. What is the correct way to deal with this? Should I add ``doesn`` to the list of valid spellings, or is there a smarter way to fix this?

**Comment by astrofrog** [comment]
@dhellmann - do you have any suggestions for dealing with this correctly?

**Comment by dhellmann** [comment]
The ContractionFilter (https://github.com/sphinx-contrib/spelling/blob/master/sphinxcontrib/spelling/filters.py#L44) is meant to address this. It looks like it's missing some common contractions though (the 2 examples you give are not included).

**Comment by dhellmann** [comment]
See https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#word-filters for setup instructions to enable the filter.

**Comment by dhellmann** [comment]
I think #30 resolves this by adding more contractions. Please re-open the issue if it does not.
