### ISSUE TITLE
Add caption nodes to the list of TEXT_NODES

### ISSUE THREAD

**Issue by paddy-hack** [sphinx-contrib/spelling#36]
Spotted a misspelling in one of my figure captions *after* fixing everything reported by
``` sh
sphinx-build -M spelling . _build/
```
:sob:

**Comment by dhellmann** [comment]
That looks like it would be a straightforward change. Do you want to propose a patch? Are there other node types being left out?

**Comment by paddy-hack** [comment]
So straightforward I cannot be bothered to fork and submit a merge request :wink:
`TEXT_ NODES` is in `sphinxcontrib/spelling/builder.py` and adding `'caption'` to that set does the trick for me.
As for other nodes left out I have no idea.  Table captions are converted to `title` nodes.

**Comment by dhellmann** [comment]
This work was released in 7.5.0
