### ISSUE TITLE
Running linkcheck before spelling breaks contraction filtering

### ISSUE THREAD

**Issue by paddy-hack** [sphinx-contrib/spelling#37]
I kept getting spelling errors like
``` console
api.rst:756:shouldn:                                                   
api.rst:756:doesn:
api.rst:1516:doesn:
api.rst:2522:isn:
```
After some searching (found #22, am using 4.3.0) and head-banging, I finally discovered that appears to be caused by me running
``` sh
sphinx-build -M clean . _build/
sphinx-build -M linkcheck . _build/
sphinx-build -M spelling . _build/ -W --keep-going
```
If I skip `linkcheck` (and run it after `spelling`) the spelling errors go away.  Alternatively, nuking `_build/doctrees/` between the `linkcheck` and `spelling` runs also makes the spelling errors go away.  BTW, it is *not* `linkcheck` specific.  I get the same behavior when running `spelling` after conversion to `html` or `latexpdf` and guess that it happens with any other builder (that creates a doctree) as well.

I'm not sure this is `spelling`'s fault and don't know whether there's anything that can be done about this but it should probably be noted somewhere at the very least.

**Comment by dhellmann** [comment]
We don't see this behavior in the doc build for this repo. tox.ini runs an HTML build and then a spelling build.

I wonder if there is some difference in the configuration causing what you're seeing? Could you post (or link to) your conf.py file?

**Comment by dhellmann** [comment]
I can't reproduce this problem locally or in CI (see #163). I suspect it has something to do with your build environment or some other extension in your build. If it's still a problem for you and you can create a minimal environment for reproducing it please let me know and I'll look at it again.
