### ISSUE TITLE
With a spelling_filter configuration is used, sphinx invalidates files on every build

### ISSUE THREAD

**Issue by ankostis** [sphinx-contrib/spelling#39]
If i modify the  `spelling_filters` configuration value is set my `conf.py` file, like that:
```python
spelling_filters = [MentionFilter, URLFilter]
```

then Sphinx up-to-date check fails and recognizes all source files as needing a rebuild.

I noticed this message: 
    [config changed ('spelling_filters')] 8 added, 0 changed, 0 removed

...and then the regular sphinx percentage spinner kicks in for all my 8 rst documents.

To debug it, apart from the message above, i appended this function at the bottom of my `docs/sources/conf.py` file to listen to the `env-get-outdated` event:
```python
def setup(app: Sphinx):
    # for documenting the configurations of the new `graphtik` directive.
    def listen(*args):
        breakpoint()
        return []

    app.connect("env-get-outdated", listen)
```
and all 8 files are always in the 1st set `added` (as seen with the *pdb* command when the breapoint kicks in: `p args`).

### Versions
```
Sphinx                             3.0.0        
sphinx-autobuild                   0.7.1        
sphinx-rtd-theme                   0.4.3        
sphinxcontrib-applehelp            1.0.2        
sphinxcontrib-devhelp              1.0.2        
sphinxcontrib-htmlhelp             1.0.3        
sphinxcontrib-jsmath               1.0.1        
sphinxcontrib-qthelp               1.0.3        
sphinxcontrib-restbuilder          0.2          
sphinxcontrib-serializinghtml      1.1.4        
sphinxcontrib-spelling             4.3.0       
```

**Comment by dhellmann** [comment]
Changing the config should trigger a rebuild, so that's normal.

Which builder is hanging? What command are you running?

**Comment by ankostis** [comment]
(Maybe i'm not fully understood.)
I'm not *continiusly* changing the config; the `conf.py` is edited only once, e.g. to add the extension & the filter,.  The described behavior would be ok if it happened only on the 1st build.
But it keeps happening for all subsequent builds, even if restarting with a clean build directory.

Also, nothing is hanging - it's just that the environment up-to-date check fails, and Sphinx (& extensions) always receive a clean environment, all pickled data from previous builds are gone.

I'm running the regular builder for rendering the site  `python setup.py build_sphinx` (not the spelling builder).
And that's the problem, because a side-effect of the extension spills to the normal operation of site-generation .

**Comment by dhellmann** [comment]
It looks like the problem is the custom filter classes added in your conf.py. They're classes, so their hash values change on each import. That means the configuration of your project appears to change on each import. I'll see if I can think of a way to allow custom classes using values that won't change.

**Comment by ankostis** [comment]
It happened also with existing filter-classes alone.

**Comment by dhellmann** [comment]
The patch in #40 works for me if I change the spelling_filters list to look like

```
spelling_filters = [
    'smallwordfilter.SpellingFilter',
    'enchant.tokenize.MentionFilter',
    'enchant.tokenize.URLFilter',
]
```

and add this line near the top of the file

```
sys.path.append(os.path.abspath("_exts"))
```

then move the SpellingFilter class and its required imports into a file called `docs/source/_exts/smallwordfilter.py` so it can be imported separately.

(Sorry, I would prepare a PR against your project but untangling the conflicts needed to revert removing the spelling checker was going to take more time than I have today.)

After making those changes, and with patch #40 in place, I can run `python setup.py build_sphinx` and see that the builder reuses the cached output from a previous run.

**Comment by dhellmann** [comment]
Release 5.0.0 of sphinxcontrib-spelling should resolve this, with the instructions given above.

**Comment by ankostis** [comment]
Wouldn't be simpler to explain in the documentation that any filter class must be discarded from the  `conf.py` globals after it is used?
