### ISSUE TITLE
Invalid `python_requires` metadata stating the supported Python runtimes

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/spelling#48]
One of the factors `pip install` uses to identify if a given version is compatible with the current Python runtime is [`python_requires` entry](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords). It is strongly recommended to add something like `python_requires='>=3'` whenever you drop support for Python 2 (same stands for other versions, of course).

If it's not set, pip will assume that the given version is compatible with Python 2 and will select it for installation regardless of whether the code in the dist is compatible with it. So this leads to having broken installs for users.

I noticed that you removed Python 2 support via https://github.com/sphinx-contrib/spelling/pull/33 and https://github.com/sphinx-contrib/spelling/pull/47/files. And you removed the corresponding [Trove classifier entry](https://pypi.org/help/#trove-classifier) but that's not enough.
Trove-classifiers are only used as tags/categories for search on PyPI. pip doesn't take them into account at all.

This is also visible at https://pypi.org/project/sphinxcontrib-spelling/5.1.0/ — there's no "Python requires" entry in the left column. For example, if you look at https://pypi.org/project/CherryPy/18.6.0/, you'll see that it requires Python `>= 3.5`.

How to fix this
=============

1. Add `python_requires` to your `setup.cfg`.
2. Cut a new release and verify that "Python requires" is present (note: PyPI reads this metadata from wheels, not sdists, so make sure to have them uploaded too)
3. Modern pip + modern Warehouse (PyPI) now implement support for ["yanking" releases] ([PEP 592]) and you should use it: just hit the "Yank" button on PyPI for the "broken" releases. This will make sure sure that those will not get `pip install`ed by accident (unless users will specify the exact version in their pins, as in `== 5.1.0`). It's better than deleting because it keeps the release available on PyPI (it will just have a special label on the UI).

[PEP 592]: https://www.python.org/dev/peps/pep-0592/
["yanking" releases]: https://pypi.org/help/#yanked

**Comment by dhellmann** [comment]
Thanks for this bug report and the very helpfully detailed instructions for fixing it!

**Comment by dhellmann** [comment]
The fix is released as part of 5.1.1.

Pulling packages from pypi gives me the chills, so I'm going to leave the existing releases up unless they're considered so completely broken that they're unusable.

**Comment by webknjaz** [comment]
@dhellmann just to be clear: I didn't suggest deleting. "yanking" is not removing anything. Things will be there and listed in the list of releases. Just marked with a yanked label. It mostly means that users shouldn't try installing them. But if they do so, they'll get those versions as they are not deleted.

The only difference would be for the recent pip versions. When users will do something like `pip install sphinxcontrib-spelling` it'll skip those versions while using `pip install sphinxcontrib-spelling==5.1.0` will install that version, no questions asked.
That's where it's different from deleting (which will effectively make pip say "hey, that version doesn't exist").

**Comment by webknjaz** [comment]
As an example, I have a yanked release `0.0.0` here: https://pypi.org/project/ansible-collections.python.dist.boo/#history.

**Comment by dhellmann** [comment]
Ah, I didn't realize yanking was different from deleting. I've yanked 5.0.0 and 5.1.0. Thanks for the tip!
