### ISSUE TITLE
misspellings do not create an error

### ISSUE THREAD

**Issue by gonsie** [sphinx-contrib/spelling#52]
The example on the [Running](https://sphinxcontrib-spelling.readthedocs.io/en/latest/run.html) documentation page shows that a misspelling will cause a make error. However, I’m not seeing that behavior. Instead, I get the following message and an 0 exit code.

```
Spelling checker messages written to /Users/gonsie/xxx/_build/output.txt
WARNING: Found 5 misspelled words
```

- sphinx-contrib.spelling version 5.1.1
- python version 3.7.7

**Comment by dhellmann** [comment]
Try adding the `-W` option to `sphinx-build` and see if that does it. Perhaps the docs are out of date with current sphinx behavior.

**Comment by gonsie** [comment]
That works, thank you! I’ll add a PR to fix the documentation.
