### ISSUE TITLE
5.1.2: requires sphinx_project module

### ISSUE THREAD

**Issue by kloczek** [sphinx-contrib/spelling#58]
I cannot find `sphinx_project` module.
Is it some bub or I'm blind and by this I cannot find that module? :)

**Comment by dhellmann** [comment]
Do you have an error message for that? I don't know what the `sphinx_project` module is either.

**Comment by kloczek** [comment]
For some reason rpm dependency generator generates requires list with `python3dist(sphinx_project)`.
I cannot find so far now why.
I see that `sphinx_project` is used in installed `%{python3_sitelib}/sphinxcontrib/tests`
BTW does this test direcoty contain sphinxcontrib spelling test suite ot it is something which can be used by other modules?

**Comment by dhellmann** [comment]
> For some reason rpm dependency generator generates requires list with `python3dist(sphinx_project)`.
> I cannot find so far now why.
> I see that `sphinx_project` is used in installed `%{python3_sitelib}/sphinxcontrib/tests`

There is a `sphinx_project` function defined in sphinxcontrib/spelling/tests/test_builder.py. I don't see any `import` statements with `sphinx_project`.

> BTW does this test direcoty contain sphinxcontrib spelling test suite ot it is something which can be used by other modules?

I don't have anything in this git repository in `sphinxcontrib/tests`. There is a `sphinxcontrib/spelling/tests` directory.

I wonder if the RPM packaging tools are confused by the fact that `sphinxcontrib` is a namespace package?

**Comment by kloczek** [comment]
Sorry mistake. I'm talking about content of the https://github.com/sphinx-contrib/spelling/tree/master/sphinxcontrib/spelling/tests which is installed on my system in /usr/lib/python3.8/site-packages/sphinxcontrib/spelling/tests/.
Is that directory content will be used by other module ot will be used by sphinx contrib spelling module?
If it is sphinx contrib spelling it could be skipped on packaging (of maybe even could be not installed at all).

I cannot reporoduce now on building rpm package to have produced package with `python3dist(sphinx_project)`. :/
I think that I've read some output incorrectly so that part is gone now, and whole ticked can be closed :P 
However it would be good to know what is the role of that test directory content :)

**Comment by dhellmann** [comment]
The content of the `sphinxcontrib/spelling/tests` directory is only meant to be used by this package, and it shouldn't be needed by anything at runtime so if you want to skip packaging it that should be OK.

**Comment by kloczek** [comment]
OK so I'm going to add that directory to exclude list on making rpm package.
Maybe it would be good to skip that part on install?

Thank you for you time and sorry but looks like it was my mistake :/
I'll close this ticket.
