### ISSUE TITLE
automatically include contributor names as spelled correctly

### ISSUE THREAD

**Issue by dhellmann** [sphinx-contrib/spelling#60]
Pull names of authors and committers of patches in git.

**Comment by webknjaz** [comment]
FTR here's how one can extract such a list:
```console
$ git log '--pretty=format:%(trailers:key=Co-Authored-By,separator=%x0A)%x0A%an <%ae>%x0A%cn <%ce>' | sort | uniq
```

**Comment by dhellmann** [comment]
Ah, I wondered about getting the co-authored-by tags. The `trailers` part is a nice tip. Thanks!

**Comment by webknjaz** [comment]
Yeah, I've been exploring this when working on a huge repo split earlier this year (https://github.com/ansible-community/collection_migration/pull/497) so I thought I'd share some of the findings :)

**Comment by dhellmann** [comment]
This was done in #68
