### ISSUE TITLE
No output.txt file, only getting a tree of *.spelling files

### ISSUE THREAD

**Issue by caddac** [sphinx-contrib/spelling#63]
I'm running the command `spinx-build -b spelling -d _build/doctree . _build/spelling` and I get a tree of files showing the misspellings per file, but no output.txt file with all the misspelled words. The docs seem to indicate I should get such a file. 

Any idea why not?

**Comment by dhellmann** [comment]
This is a documentation bug. I thought I updated that, but must not have.

As part of supporting parallel builds, the output now goes to separate files named based on the input files. I know it's not ideal, so suggestions most definitely welcome for improving that experience.

**Comment by caddac** [comment]
I think not outputing blank files would go a long way. As of now I get an output file for every input file, but most are blank. So I have to go through them one by one to find where the spelling error is.

**Comment by dhellmann** [comment]
Yeah, that's definitely something I could look at.
