### ISSUE TITLE
Useful snipit of code for conf.py

### ISSUE THREAD

**Issue by markcmiller86** [sphinx-contrib/spelling#8]
Thanks so much for sphinxcontrib.spelling!!

I have a snipt it of code you might find useful to offer here and wasn't sure best way to provide it.

The issue I had was using your spell checker in a situation where many developers are writing documentation and I don't want to burden all of them with having to install added dependencies to support it. And, that kinda sorta becomes necessary of the `.. spelling::` directive is used anywhere.

Here is what I did...

Added following code to `conf.py` to effectively *disable* `.. spelling::` directives by default.

```
#
# NO-OP the .. spelling:: directive for normal use
# spell_check.sh removes the call to app.add_directive
# before running sphinx-build.
#
def setup(app):
    app.add_directive('spelling', SpellingDirective)
    pass # Here so line above can be removed during spell check

from docutils.parsers.rst import Directive

class SpellingDirective(Directive):

    has_content = True

    def run(self):
        return []
```

Wrote a tiny shell script that copies `conf.py` to a temporary dir and then sed-modifies it to *remove* the `app.add_directive` and *add* the extension to the `extensions` variable...

```
#!/bin/sh

# Make a temporary dir for the adjusted conf.py file
tempfoo=$(basename $0)
TMPDIR=$(mktemp -d -t ${tempfoo}) || exit 1

#
# Copy conf.py and sed-replace the extensions variable
#
cat conf.py | sed \
    -e "s/^extensions[[:space:]]*=[[:space:]]*\[\(.*\)\]/extensions = [\1, 'sphinxcontrib.spelling']/" \
    -e "s/^    app.add_directive('spelling', SpellingDirective)//" \
    > ${TMPDIR}/conf.py

#
# Run Sphinx with spell-check builder
#
sphinx-build -c ${TMPDIR} -b spelling . _spelling
rm -rf ${TMPDIR}
```

This makes is possible to free everyone on team (and RTD server setup too) from *having* to install the additional libraries but still get the great spell checking your tool provides.

Thanks again!

**Comment by dhellmann** [comment]
I wonder if you could achieve the same thing using a configuration option or environment variable, to avoid having to modify conf.py as part of the build?

**Comment by markcmiller86** [comment]
I don't know. There may be better ways of handling it.  I guess using an env. variable I could just add logic directly to conf.py that either did or did not add the extension and did or did not define the no-op `.. spelling::` directive. That would make copying conf.py unnecessary.

**Comment by markcmiller86** [comment]
Actually, can probably do better. I just need to check if sys.argv includes '-b' followed by 'spelling' and then do the right thing. Thanks for suggestion.

**Comment by markcmiller86** [comment]
Ok, so this works and is *better* in that we don't need a shell script.

Here are mods to conf.py

Near the top...

```
import sys

BuilderIsSpelling = False
if '-b' in sys.argv and 'spelling' in sys.argv:
    if sys.argv.index('-b') == sys.argv.index('spelling')-1:
        BuilderIsSpelling = True
```

For extensions variable...

```
extensions = ['sphinx.ext.mathjax']
if BuilderIsSpelling:
    extensions += ['sphinxcontrib.spelling']
```

And for `.. spelling::` directive...

```
#
# NO-OP the .. spelling:: directive for normal use
# spell_check.sh removes the call to app.add_directive
# before running sphinx-build.
#
def setup(app):
    if not BuilderIsSpelling:
        app.add_directive('spelling', SpellingDirective)

from docutils.parsers.rst import Directive

class SpellingDirective(Directive):

    has_content = True

    def run(self):
        return []

```

A normal html build `sphinx-build -b html . _build` will work fine and **not require** the extensions for spelling checking.

A spell check build, `sphinx-build -b spelling . _spelling` will run correctly if the extension is available or fail with message...

```
Extension error:
Could not import extension sphinxcontrib.spelling (exception: No module named sphinxcontrib.spelling)
```
