### ISSUE TITLE
Mark single word as correctly spelled

### ISSUE THREAD

**Issue by koebi** [sphinx-contrib/spelling#9]
It might happen that a file contains correctly spelled words that are wrong spellings of another word.
For example, one might want to write the sentence "A common misspelling for the word contains is contians."
Of course, sphinxcontrib-spelling should report an error for any other occurrence of "contians" outside of our intentional typo, but it shouldn't report an error for our intentional typo.

Is there any possibility to realize this in the current version of sphinxcontrib-spelling?
If not, would it be possible to use a rst-substitution in combination with the spelling directive to realize this?

I'm thinking along the lines of:

    .. |contians| spelling:: contians

    A common misspelling for the word contains is |contians|."

In this example, the substituted `|contians|` would be replaced by the data in the substitution definition (see [documentation](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions)), the spelling directive would tell sphinxcontrib-spelling that this word is to be used "as is" for this one occurrence.

**Comment by dhellmann** [comment]
Words wrapped in double back-ticks to indicate they are literal values are not spell checked. Could you use that?

**Comment by koebi** [comment]
Hey, thanks for the suggestion. I tried, but that leads to the word being highlighted differently than normal text, so for my case this is unfortunately not an option :(

**Comment by dhellmann** [comment]
I suppose we could have the extension module define a new role like :spelling-ignore:`contians` that does not apply any styling but ignores the word. Let me know if you want to work on something like that and I will review the patches.

**Comment by paddy-hack** [comment]
Just a thought but what about using the `spelling` directive in the file with the intentionally misspelled word?

See https://sphinxcontrib-spelling.readthedocs.io/en/latest/customize.html#private-dictionaries

**Comment by webknjaz** [comment]
> Just a thought but what about using the `spelling` directive in the file with the intentionally misspelled word?

I guess that would not work if you want to ignore it only in one sentence but not the whole file. A role sounds more reasonable. It could even apply some `class="misspelled"` in HTML but not provide any CSS for that, leaving it to the users to highlight it or not.

**Comment by dhellmann** [comment]
This feature was added in release 7.6.0
