### ISSUE TITLE
[6.0.0] `importlib.util.find_spec` raises ValueError (it was not a case with `imp.find_module`)

### ISSUE THREAD

**Issue by amureki** [sphinx-contrib/spelling#96]
Greetings!
Thakns for maintaining this package! ✨ 

While trying new version 6.0.0, we discovered the next issue:

```
Exception occurred:
  File "/opt/python/3.8.6/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: celery.__spec__ is None
```

I did try to dig a bit and discovered, that new `importlib.find_spec` raises `ValueError` in case [the spec would be None or is not set](https://docs.python.org/3/library/importlib.html#importlib.util.find_spec). The change related to it was introduced in #73.

This behaviour differs from `imp.find_module`, where it was returning None or raising `ImportError`.

Seems like we need to update this bit in spelling library to cover new behaviour.

Cheers,
Rust

**Comment by dhellmann** [comment]
The fix you've provided is included in release 7.0.0, so I'm going to close this issue. I think this is the same as #95, which I am leaving open until the reporters there can confirm that the fix also solves the problem for them.

Thanks again for finding and fixing the problem!
